[app]
table-thread = 3
sql-thread = 1024
batch-size = 500
chunk-size = 200000
sql-hint = "/*+ PARALLEL(8) */"
skip-init = false
call-timeout = 999999999999

[oracle]
username = "findpt"
password = "findpt"
host = "10.2.103.33"
port = 1521
service-name = "gbk"
#pdb-name = ""
charset = "zhs16gbk"
session-params = []
schema = "findpt"

[mysql]
username = "root"
password = ""
host = "120.92.19.233"
port = 4000
connect-params = "multiStatements=true&parseTime=True&loc=Local"
charset = "utf8mb4"
schema = "scans"

[meta]
username = "root"
password = ""
host = "120.92.19.233"
port = 4000
slow-threshold = 300
meta-schema = "scandb"


[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./scan-server.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-days = 7
# 日志文件最多保存多少个备份
max-backups = 30